name: tomo
description: "Um aplicativo financeiro."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
   - assets/images/adventure-map.png
   - assets/images/castle.png
   - assets/images/magic.png
   - assets/images/monster.png
   - assets/images/sorceress.png
   - assets/images/spell-book.png
   - assets/images/spell-book-Logo.png
   - assets/images/armor.png
   - assets/images/elf.png
   - assets/images/grim-reaper.png
   - assets/images/item-bag.png
   - assets/images/king.png
   - assets/images/knight.png
   - assets/images/medusa.png
   - assets/images/orc.png
   - assets/images/poison-spider.png
   - assets/images/viking.png
   - assets/images/villager.png
   - assets/images/werewolf.png
  fonts:
    - family: Roboto-Light
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
    - family: Roboto-Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto-Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: JetBrainsMono-Regular
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
    - family: JetBrainsMono-Light
      fonts:
        - asset: assets/fonts/JetBrainsMono-Light.ttf
    - family: JetBrainsMono-Bold
      fonts:
        - asset: assets/fonts/JetBrainsMono-Bold.ttf

flutter_native_splash:
  color: "#85365d"
  image: assets/images/spell-book.png
  android_12:
    image: assets/images/spell-book.png
    color: "#85365d"